project:
  output-dir: _book
  type: book

toc: true
number-sections: false
citation: 
  license: "CC BY-NC-ND 4.0"
  type: "book"
  author: Edgar E. Gareca
  collection-title: Liturgia para ministerios de música católicos
  issued: NA
  abstract: |
    Liturgia en lenguaje sencillo para el ministerio de música católicos

citation-location: document
lang: es

book:
  title: "Liturgia para ministerios de música católicos"
  downloads: [pdf]
  author:
    - name: "Edgar E. Gareca León"
      url: https://www.researchgate.net/profile/Edgar-Gareca-Leon
      affiliation: Fraternidad de laicos Santo Tomás de Aquino, Cochabamba
    - name: "Colaborador"
  ## description: "Lo que quieras decir"
  page-footer:
    left:
      - text: "&copy; Edgar E. Gareca León, OP"
  date: last-modified
  date-format: "[Última modificación:] DD-MM-YYYY: H:mm:ss (A)"
  reader-mode: true
  repo-url: https://github.com/edgarle/litmus/
  repo-actions: [edit, issue]
  cover-image: cover.png
  chapters: 
    - index.qmd
    - intro.qmd
    - minmus.qmd
    - liturgia.qmd
    - misa.qmd
    - minmus-otros.qmd
  references: referencias.bib
  appendices:
    - referencias.qmd
    - textos-ordinario.qmd
  back-to-top-navigation: true
  page-navigation: true
  search: true
  sharing: [twitter, facebook]
  cover-image-alt: |
    Descripción de la tapa
format:
  html:
    link-external-icon: true
    shift-heading-level-by: 0
    subject: "Liturgia para músicos"
    date: last-modified
    date-format: "[Última modificación:] DD-MM-YYYY: H:mm:ss (A)"
    theme:
      light: [simplex, litmus-light.scss]
      dark: simplex
    code-tools: false
    df-print: paged
    fig-cap-location: bottom
    # html-math-method: mathjax
    number-sections: true
    number-depth: 2
    toc-depth: 3
    # reference-location: 
  pdf:
    toc: true
    fig-pos: "H"
    hyperrefoptions:
      - bookmarksnumbered=true
    toc-title: Contenidos
    df-pring: tibble
    links-as-notes: true
    documentclass: scrbook
    classoption: [twoside=off]
    shift-heading-level-by: 0
    toc-depth: 1
    number-sections: false
    number-depth: 3
    colorlinks: true
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
  


