# ¿Por qué debemos conocer al año litúrgico?
Después de conocer la importancia de la música en la misa (LINK) y el rol del ministerio de música (LINK),
te muestro  cómo el conocer el año litúrgico nos da pautas generales para cumplir nuestro rol.

El año litúrgico nos permite crecer en los tres ámbitos: musical, litúrgico y espiritual.

Hijo, no te preocupes de las canciones que cantarás hoy, ya las conoces;
preócupate por tu estado de ánimo con el que las cantarás. (CITA ANTONY DE MELLO)

## Tiempo de Adviento
Inicio del año litúrgico y es un tiempo de espera y de esperanza

### Temática de los cantos del tiempo de Adviento

## Tiempo de Navidad
El Hijo de Dios se hace hombre, hay un Dios entre nosotros.
Dios Padre nos ama tanto que envía a su Hijo a nuestro mundo,
el Hijo nos ama tanto que siendo Dios se hace hombre.
_Ya vislumbra la noche de la Vigilia Pascual_

### Octava de Navidad

### Temática de los cantos del tiempo de Navidad

## Tiempo Ordinario 1
Es variable y trata de las temáticas...
Son pocos domingos

### Temática de los cantos del tiempo Ordinario

## Tiempo de Cuaresma
Tiempo espera y preparación
Inicio miércoles de ceniza
### Temáticas de los cantos del tiempo de Cuaresma

## Semana Santa
Es el centro de nuestra fe
En ella se sintetiza y manifiesta plenamente el amor que Dios nos tiene.
El Hijo ama tanto a su Padre y al hombre que muere por obediencia al primero
y por amor a los segundos. 

### Domingo de Ramos
Entrada triunfal de Jesús a Jerusalén

#### Temática de los cantos del Domingo de Ramos

### Triduo Pascual

### Jueves Santo
La institución de la Eucaristía y la institución del orden sacerdotal

#### Temática de los cantos del Jueves Santo

#### Temática de los cantos para acompañar al Santísimo después de misa

### Viernes Santo
Muerte de Jesús
Adoración de la cruz

#### Temática de los cantos para la adoración de la cruz

### Vigilia Pascual
Recordamos la antigua alianza y celebramos la nueva alianza
Celebramos la resurrección de Jesús

#### Pregón Pascual

#### Notas sobre el momento de la aspersión con agua bendita

#### Momento de gozo que puede celebrarse con el ministerio de música

### Sábado Santo
Esta sección no está destinado a las canciones o música,
sino al rol de este momento en la Semana Santa

## Tiempo de Pascua

### Domingo de Pascua
Aparición de Jesús a las mujeres

### Octava de Pascua

### Ascensión del Señor al cielo

## Pentecostés
Cumpleaños de la Iglesia, nuestro cumpleaños como Iglesia

### Vigilia de Pentecostés 

### Momento de gozo que puede celebrarse con el ministerio de música

## Tiempo Ordinario 2
Ocupa el resto del año hasta la fiesta de Cristo Rey

## Otras fiestas de la Iglesia

### /Corpus Christi/

### Sagrado corazón de Jesús y María

### Fiestas patronales

### Sirviendo o ¿MINISTRANDO? en los Sacramentos

#### Bautizo

#### Primera comunión

#### Confirmación

#### Matrimonio