# Liturgia para ministerios de música
A continuación se presentan algunos elementos básicos de liturgia para ministerios de música y fieles laicos. La finalidad es que entendamos mejor nuestro rol, tanto como laico y ministerio de música.  Pero más aún, que descubramos las maravillas que esconde la liturgia para nosotros, los creyentes en Cristo Jesús.

## ¿Qué es la liturgia? {#sec-liturgia}
La liturgia es...

### La misa es liturgia

### En la misa debemos cantar música litúrgica
(¿Qué es la música litúrgica, católica y "cristiana"?)
Esta pregunta la tomé de un video de Youtube (ENLACE)
y tiene la finalidad de ayudarte a comprender porqué en la misa debemos cantar música litúrgica,
y cuál es la ventaja de diferenciar entre música católica de la música "cristiana".

## El año litúrgico
Después de conocer la importancia de la música en la misa (LINK) y el rol del ministerio de música (LINK),
te muestro  cómo el conocer el año litúrgico nos da pautas generales para cumplir nuestro rol.

El año litúrgico nos permite crecer en los tres ámbitos: musical, litúrgico y espiritual.

Hijo, no te preocupes de las canciones que cantarás hoy, ya las conoces;
preócupate por tu estado de ánimo con el que las cantarás. (CITA ANTONY DE MELLO)

### Tiempo de Adviento y sus cantos
Inicio del año litúrgico y es un tiempo de espera y de esperanza

### Tiempo de Navidad y sus cantos
El Hijo de Dios se hace hombre, hay un Dios entre nosotros.
Dios Padre nos ama tanto que envía a su Hijo a nuestro mundo,
el Hijo nos ama tanto que siendo Dios se hace hombre.
_Ya vislumbra la noche de la Vigilia Pascual_

#### Octava de Navidad

### Tiempo Ordinario y sus cantos
Es variable y trata de las temáticas...
Son pocos domingos

### Tiempo de Cuaresma y sus cantos
Tiempo espera y preparación
Inicio miércoles de ceniza

### Semana Santa y sus cantos
Es el centro de nuestra fe
En ella se sintetiza y manifiesta plenamente el amor que Dios nos tiene.
El Hijo ama tanto a su Padre y al hombre que muere por obediencia al primero
y por amor a los segundos. 

#### Domingo de Ramos
Entrada triunfal de Jesús a Jerusalén

#### Triduo Pascual - una sola celebración

##### Jueves Santo
La institución de la Eucaristía y la institución del orden sacerdotal

Cantos para la celebración
Cantos para acompañar al Santísimo después de misa
Ver también la sección "adoración al Santísimo"

##### Viernes Santo
Muerte de Jesús
Adoración de la cruz

##### Vigilia Pascual
Recordamos la antigua alianza y celebramos la nueva alianza
Celebramos la resurrección de Jesús

###### Pregón Pascual

###### Notas sobre el momento de la aspersión con agua bendita

###### Momento de gozo al final de la celebración

#### Notas del Sábado Santo
Esta sección no está destinado a las canciones o música,
sino al rol de este momento en la Semana Santa

### Tiempo de Pascua, su octava y cantos
Aparición de Jesús a las mujeres

#### Octava de Pascua

#### Ascensión del Señor al cielo

### Pentecostés
Cumpleaños de la Iglesia, nuestro cumpleaños como Iglesia

#### Vigilia de Pentecostés <! -- omit in toc --> 

#### Momento de gozo que puede celebrarse con el ministerio de música <! -- omit in toc --> 

### Tiempo Ordinario 2
Ocupa el resto del año hasta la fiesta de Cristo Rey

## Sirviendo o ¿MINISTRANDO? en los Sacramentos

### Bautizo

### Primera comunión

### Confirmación

### Matrimonio

## Otras fiestas de la Iglesia

### /Corpus Christi/

### Sagrado corazón de Jesús y María

### Fiestas patronales

