# ¿Cuáles son las partes de la misa y sus cantos?
La misa es una celebración de una comunidad,
así que las letras de las canciones deben tratar de demostrarlo.
De esta manera evitar canciones en primera persona singular: yo,
y escoger canciones en primera persona plural: nosotros.
Ya que nosotros como Iglesia
celebramos esta manifestación de Dios entre nosotros.

## Partes de la misa

### Ritos iniciales
Finalidad dentro de la liturgia

#### Canto de entrada _(O ANTÍFONA??)_

#### Kyrie o Señor piedad

#### Gloria

### Liturgia de la Palabra
Se proclama a la Palabra de Dios,
esta se consuma en el Evangelio
en la que escuchamos a Jesús,
la Palabra de Dios que se hizo carne.

#### Primera lectura
Generalmente tomada del AT
Solo en el tiempo pascual, corresponde al NT

#### Salmo responsorial
Sirve de unión o bisagra entre la primera lectura y el Evangelio

#### Segunda lectura
Corresponde al NT
No siempre se puede encontrar una relación entre esta lectura

#### Aclamación al Evangelio
Debe ser cantado
Cantar ambas secciones: "Aleluya"
y el versículo que viene en las hojas litúrgicas.
No incluir otros textos que no sean los anteriores
ya que pueden distraer al mensaje dado por las lecturas anteriores
y por tanto su unión con el Evangelio.

#### Credo
Se recomienda que se cante.

### Liturgia de la Eucaristía

#### Canto de las ofrendas

#### Santo

#### Amén
Debe ser cantado

#### Padre nuestro
Debe ser cantado

#### Saludo de paz
Durante el saludo de paz se hace uso de un recurso musical, el #silencio#.
El silencio termina cuando el presidente de la celebración está por romper
el cuerpo de Cristo.

#### Agnus Dei o Cordero
Recordamos la muerte y sacrificio de Jesús, muestra de su amor por nosotros.
No se debe aplaudir, es un momento de recogimiento.

#### Canto de comunión

### Rito de conclusión

#### Canto final
Debe tener un sentido misionero, de envío,
de dar a conocer a los demás la buena noticia que recibimos.

María es un ícono misionero y muchas de las canciones dedicadas
a la madre del Señor y madre nuestra,
pueden ser adecuadas para este fin

## Cantos en la misa

### Cantos del ordinario de la misa
Estos cantos siempre deben tener la letra que se da a continuación.

#### _Kyrie_ o Señor piedad

#### Gloria

#### Credo

#### Santo

#### Amén

#### Padre nuestro

#### _Agnus Dei_ o Cordero

### Cantos propios de la misa

#### Entrada

#### Salmo

#### Aclamación al Evangelio

#### Comunión

#### Canto final

#### Ofertorio